name: Update README cards

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch: # Permite rodar manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure profile directory exists
        run: mkdir -p profile

      - name: Generate stats card
        uses: Franklyn-R-Silva/github-readme-stats-fast-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=radical
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate streak card
        uses: Franklyn-R-Silva/github-readme-stats-fast-action@v1
        with:
          card: streak
          options: username=${{ github.repository_owner }}&show_icons=true&theme=radical
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages card
        uses: Franklyn-R-Silva/github-readme-stats-fast-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=radical
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Wakatime card
        uses: Franklyn-R-Silva/github-readme-stats-fast-action@v1
        with:
          card: wakatime
          options: username=Franklyn-R-Silva
          path: profile/wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || echo "No changes to commit"
          git push origin HEAD
